### PR TITLE
Fixing tests and Docs

### LINKED ISSUE #13: Improve tests
Trying to find a solution for [this](https://github.com/TornaxO7/himalaya/blob/mail_refactor/src/config/model.rs#L150) case for example. Also thinking about a `test` trait... or not...

### PR DESCRIPTION
**Pull request by TornaxO7**
- Provided more docs
- Refactored tests and added more tests

### CODE REVIEW

**Comment by TornaxO7** [comment]
@soywod  Review pls

PS: You were right, we don't need another `Test` trait. I created the needed default-functions in the test modules. :+1:

File: src/config/model.rs [hunk 1]
```diff
@@ -367,16 +353,60 @@ impl Config {
...
+    ///
+    ///     assert_eq!(config.address(&normal_account), "Acc1 <acc1@mail.com>");
+    ///     assert_eq!(config.address(&special_account), "\"TL;DR\" <acc2@mail.com>");
+    /// }
+    /// ```
     pub fn address(&self, account: &Account) -> String {
         let name = account.name.as_ref().unwrap_or(&self.name);
+
+        let special_chars: Vec<&str> = name
+            .matches(|character| ",.:;".contains(character))
```
Comment (soywod) [inline src/config/model.rs]: Where did you get this information? I tried to search into the [RFC 5322](https://datatracker.ietf.org/doc/html/rfc5322) but I did not find those chars.

File: src/config/model.rs [hunk 2]
```diff
@@ -367,16 +353,60 @@ impl Config {
...
+            .collect();
+
         if name.is_empty() {
             format!("{}", account.email)
+        } else if !special_chars.is_empty() {
+            // so the name has special characters => Wrap it with '"'
+            format!("\"{}\" <{}>", name, account.email)
```
Comment (soywod) [inline src/config/model.rs:398]: Maybe the simpler would be to always quote the display name, what do you think? See https://stackoverflow.com/a/15606313/6213048.

**Review by soywod — CHANGES_REQUESTED** [review]

File: src/config/model.rs (hunk 1 above)
Comment (TornaxO7) [reply src/config/model.rs]: I remembered that you should quote the name, if it includes some special characters. I just remembered those. Now after a quick lookup I found [this](https://datatracker.ietf.org/doc/html/rfc2822#section-3.2.1). Looks like that we'll have to expand the list :D

File: src/config/model.rs (hunk 2 above)
Comment (TornaxO7) [reply src/config/model.rs:398]: Hm... I'm a little bit unsure about this because if we take a look [on the examples](https://datatracker.ietf.org/doc/html/rfc2822#appendix-A) then we can see that the names are quoted, if they include these preserved characters (like the dot or comma). Personally I'd prefer to use the quotes if they're necessary but feel free to decide. I accept quotes as ^^

Comment (soywod) [reply src/config/model.rs:398]: I just try to find a good compromise between value of feature and time spent, we see how complex and full of details those RFC are. Putting quotes avoid invalid names. Putting quotes around a name that does not need them seems not to make it invalid either. Knowing that, do you think it's worth spending time digging the RFC to have a perfect working model (with tests) rather than just putting quotes ? I'm open to discussion ofc, I may be wrong there, it is just my opinion.

Comment (TornaxO7) [reply src/config/model.rs:398]: So you'd prefer to have always quotes?

Comment (soywod) [reply src/config/model.rs:398]: As you wish. I don't want to force anything. After all, if it's just chars to check then it's okey, you can leave this way.

File: src/config/model.rs [hunk 3]
```diff
@@ -367,16 +353,60 @@ impl Config {
...
+    ///     };
+    ///
+    ///     assert_eq!(config.address(&normal_account), "Acc1 <acc1@mail.com>");
+    ///     assert_eq!(config.address(&special_account), "\"TL;DR\" <acc2@mail.com>");
+    /// }
+    /// ```
     pub fn address(&self, account: &Account) -> String {
         let name = account.name.as_ref().unwrap_or(&self.name);
+
+        let special_chars: Vec<&str> = name
```
Comment (soywod) [inline src/config/model.rs]: I think the algorithm can be improved here. We don't need to collect _all_ special chars, we just need to know if there is _at least_ one. What about sth like `let has_special_chars = name.contains(|c| "()<>[]:;@.,".contains(c));`?

**Review by soywod — CHANGES_REQUESTED** [review]

**Comment by TornaxO7** [comment]
@soywod update!

**Review by soywod — APPROVED** [review]
