### PR TITLE
Fixing json output html

### LINKED ISSUE #5: Read
- [x] The JSON output does not have the same shape (it misses `hasAttachment`)
- [x] The JSOn output should show the `text/html` version of the mail if no `text/plain` is found.

### PR DESCRIPTION
**Pull request by TornaxO7**
Should fix [this issue](https://github.com/TornaxO7/himalaya/issues/5).

### CODE REVIEW

**Comment by TornaxO7** [comment]
Summary: 
- JSON Output includes `hasAttachment` now
- JSON output gives `text/html` and `text/plain` back

**Comment by TornaxO7** [comment]
@soywod review pls

File: src/msg/body.rs [hunk 1]
```diff
@@ -24,91 +23,130 @@ error_chain! {
...
-        &self.0
-    }
-}
-
-impl DerefMut for Body {
-    fn deref_mut(&mut self) -> &mut Self::Target {
-        &mut self.0
-    }
-}
+        let content = if let Some(text) = self.text.clone() {
```
Comment (soywod) [inline src/msg/body.rs:141]: This means that the `text` version of the body will always be taken first. In fact, it should show the text or the html depending on this argument https://github.com/soywod/himalaya/blob/608057b23bcd067e6f5fe130c6e395655432a448/src/msg/cli.rs#L112-L119.

File: src/msg/model.rs [hunk 2]
```diff
@@ -36,9 +35,8 @@ use colorful::Colorful;
 // == Macros ==
 error_chain::error_chain! {
     errors {
-        // An error appeared, when it tried to parse the body of the msg!
         ParseBody (err: String) {
-            description("Couldn't get the body of the parsed msg."),
+            description("An error appeared, when it tried to parse the body of the msg!"),
```
Comment (soywod) [inline src/msg/model.rs]: Try to align with other errors (I mean, the style of the message).

File: src/msg/model.rs [hunk 3]
```diff
@@ -275,14 +271,14 @@ impl Msg {
 
         // comment "out" the body of the msg, by adding the `>` characters to
         // each line which includes a string.
-        let mut new_body = self
-            .body
+        let mut new_body = self.body.text.clone()
+            .unwrap_or(String::new())
```
Comment (soywod) [inline src/msg/model.rs]: `unwrap_or_default` should work here?

File: src/msg/model.rs [hunk 4]
```diff
@@ -728,6 +732,23 @@ impl Msg {
 }
 
 // -- Traits --
+impl ser::Serialize for Msg {
+    fn serialize<S> (&self, serializer: S) -> core::result::Result<S::Ok, S::Error>
+    where
+        S: ser::Serializer
+    {
+        println!("ÖLKJASFÖLKJ");
```
Comment (soywod) [inline src/msg/model.rs]: :thinking:

File: src/msg/model.rs [hunk 5]
```diff
@@ -728,6 +732,23 @@ impl Msg {
 }
 
 // -- Traits --
+impl ser::Serialize for Msg {
```
Comment (soywod) [inline src/msg/model.rs]: Isn't possible to have a dedicated struct to avoid implementing the Serialize trait? See https://github.com/soywod/himalaya/issues/153.

**Review by soywod — CHANGES_REQUESTED** [review]
I think there is still an issue with the formatting, could you check if the config file is taken into consideration by your IDE?

File: src/msg/body.rs (hunk 1 above)
Comment (TornaxO7) [reply src/msg/body.rs:141]: Oh yes, you're right. Thank you for pointing this out!

File: src/msg/model.rs (hunk 3 above)
Comment (TornaxO7) [reply src/msg/model.rs]: yes thanks for this hint!

File: src/msg/model.rs (hunk 4 above)
Comment (TornaxO7) [reply src/msg/model.rs]: *cough cough* eeeeeh.... I'll fix this *cough cough* (it was used to be a quick log message)

File: src/msg/model.rs (hunk 5 above)
Comment (TornaxO7) [reply src/msg/model.rs]: The reason why I implemented it manually, is because I didn't want to add another attribute for `Msg` which is only used for Serializsation. I'll add this as a comment/doc to the trait implementation.

File: src/msg/body.rs (hunk 1 above)
Comment (TornaxO7) [reply src/msg/body.rs:141]: Hm... ok so in my latest commit, I'm printing out everything of the message: Body + Headers. Do you think that this is fine?

**Comment by TornaxO7** [comment]
@soywod update

File: src/msg/body.rs (hunk 1 above)
Comment (soywod) [reply src/msg/body.rs:141]: It depends for what, I think both should be available: a simple version with only the body, and a full version with headers + body.

File: src/msg/model.rs (hunk 4 above)
Comment (soywod) [reply src/msg/model.rs]: :rofl:

File: src/msg/model.rs (hunk 5 above)
Comment (soywod) [reply src/msg/model.rs]: I still think it could be nicer to introduce a dedicated struct for this purpose, sth like:

```rust
#[derive(Serialize)]
struct SerializableMsg {
    #[serde(flatten)]
    inner: Msg,
    has_attachments: Bool,
}
```

It's better to let the `serde` lib do it's job rather than implementing ourselves Serialize.

Comment (TornaxO7) [reply src/msg/model.rs]: Btu that makes it more complicated from my point of view. Currently, we can just give `Msg` to the `Output.print` function and the method will decide if it should use the implemented serializer or the `Display` trait.

How should it be handled if you want to print out the msg? I'd need to always check which mode the printer has `Output.is_json()` and `Output.is_text()`.

File: src/msg/body.rs (hunk 1 above)
Comment (TornaxO7) [reply src/msg/body.rs:141]: So I did the following in my latest commmit:
- The `Display` trait of `Msg` is gonna return the _body_ of the message.
- I added another method: `get_full_message` which adds the headers as well.

Do you acgree with this?

File: src/msg/model.rs (hunk 5 above)
Comment (soywod) [reply src/msg/model.rs]: I'm not sure to understand your problem. Instead of passing a `Msg` to the printer, you pass a `SerializableMsg`. The only thing we need is a connector from a `Msg` to a `SerializableMsg`. It's quite common to have different struct from the same model for different purposes. At one of my work I used [`diesel`](https://diesel.rs/guides/getting-started) (it's an ORM), and it's common to have a struct for the `Queryable` trait, another one for the `Insertable` trait etc.

File: src/msg/body.rs (hunk 1 above)
Comment (soywod) [reply src/msg/body.rs:141]: Sounds great :ok_hand:

File: src/msg/model.rs (hunk 5 above)
Comment (TornaxO7) [reply src/msg/model.rs]: Could you please show my a little example what you mean? Should he `SerializeableMsg` implement the `From` trait to be used like this?
```
Output.print(SerializeableMsg::from(&msg));
```
?

Comment (soywod) [reply src/msg/model.rs]: It could be great but I'm afraid you will not be able (because you will miss the `has_attachments` that does not exists on `Msg`). A custom function will be needed.

**Comment by TornaxO7** [comment]
@soywod review pls

File: src/msg/model.rs [hunk 6]
```diff
@@ -846,18 +859,18 @@ impl TryFrom<&Fetch> for Msg {
...
-                Ok(parsed) => {
-                    debug!("Fetch has a body to parse.");
-                    Some(parsed)
-                },
-                Err(_) => {
-                    debug!("Fetch hasn't a body to parse.");
-                    None
-                },
-            };
+                // the empty array represents an invalid body, so we can enter the
```
Comment (soywod) [inline src/msg/model.rs]: Tab issue?

File: src/msg/model.rs [hunk 7]
```diff
@@ -70,9 +69,39 @@ error_chain::error_chain! {
...
+    #[serde(flatten)]
+    pub msg: Msg,
+
+    /// A bool which indicates if the current msg includes attachments or not.
+    pub has_attachment: bool,
+}
+
+impl From<&Msg> for MsgSerialized {
+    fn from(msg: &Msg) -> Self {
+        let has_attachment = msg.attachments.len() > 0;
```
Comment (soywod) [inline src/msg/model.rs]: It's a detail, but I would go with a more dedicated method `is_empty()`.

**Review by soywod — CHANGES_REQUESTED** [review]

File: src/msg/model.rs (hunk 7 above)
Comment (TornaxO7) [reply src/msg/model.rs]: Good idea!

**Comment by TornaxO7** [comment]
@soywod update

**Review by soywod — APPROVED** [review]
